function ShowHelpdialog()
%% [26-08-2025]
% show Help Dialog.


dlgWidth = 450;
dlgHeight = 400;
btnWidth = 150;
btnHeight = 35;
xCenter = (dlgWidth - btnWidth) / 2;

d = dialog('Position',[500 500 dlgWidth dlgHeight],'Name','CardioMark Help');

% Title
uicontrol('Parent',d,...
    'Style','text',...
    'FontSize',22,...
    'FontWeight','bold',...
    'HorizontalAlignment','center',...
    'Position',[25 350 400 50],...
    'String','CardioMark V1.0');

% Description
uicontrol('Parent',d,...
    'Style','text',...
    'FontSize',14,...
    'HorizontalAlignment','center',...
    'Position',[25 270 400 70],...
    'String','CardioMark: An open-source MATLAB toolbox for ECG annotation for machine learning and academic research');

% Additional Information!
uicontrol('Parent',d,...
    'Style','text', 'ForegroundColor', [1 0 0],'FontAngle','italic', ...
    'FontSize',12,'FontWeight','bold',......
    'HorizontalAlignment','center',...
    'Position',[25 200 400 70],...
    'String','This software is intended for research and educational purposes only; it is not designed for diagnostic use');

% GitHub Button
uicontrol('Parent',d,...
    'Position',[xCenter 150 btnWidth btnHeight],...
    'FontSize',13,...
    'String','GitHub',...
    'Callback',@(src,event)web('https://github.com/CardioMark/CardioMark'));

% Documentation Button
uicontrol('Parent',d,...
    'Position',[xCenter 100 btnWidth btnHeight],...
    'FontSize',13,...
    'String','Documentation',...
    'Callback',@(src,event)web('https://github.com/CardioMark/CardioMark/tree/main/Documentation'));

% OK Button
uicontrol('Parent',d,...
    'Position',[xCenter 50 btnWidth btnHeight],...
    'FontSize',13,...
    'String','OK',...
    'Callback',@(src,event)close(d));

uiwait(d);

end
